// Class: Vertex
// Used to define the vertices in digraph
// Vertex refers to the "super" nodes generated by merging multiple nodes

#ifndef _Vertex_H_
#define _Vertex_H_

using namespace std;

#include <list>
#include <vector>
#include "Locations.h"

class Vertex
{
	private:
		list<Locations> _locationsList;	// The list of k-mers

	public:
		Vertex();	// Empty constructor function
		Vertex(Locations);	// Constructor function
		Vertex(list<Locations>);	// Constructor function
		Vertex(vector<Locations>);	// Constructor function
		~Vertex();	// Destructor function
		typedef list<Locations>::iterator iterator;
		typedef list<Locations>::const_iterator const_iterator;
		iterator begin() {return _locationsList.begin(); };
		iterator end() {return _locationsList.end(); };
		int Size();	// Return the number of nodes contained in the vertex
		bool operator ==(const Vertex);	// Check whether the two vertices are equal
};

#endif
